config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'articles#index'

  resources :articles do
    resources :comments
    post 'archive', on: :member
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  include AASM

  aasm(:status) do
    state :inactive, initial: true
    state :published, :archived

    event :archive do
      transitions from: [:published, :inactive], to: :archived
    end

    event :publish do
      transitions from: :inactive, to: :published
    end
  end

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern
  extend Enumerize

  enumerize :status, in: %w[published inactive archived], predicates: false, scope: :having_status

  class_methods do
    def public_count
      having_status(:published).count
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)

      redirect_to @article
    else
      render :edit
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  def archive
    @article = Article.find(params[:id])
    @article.archive

    @article.save
    redirect_to @article
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy

    redirect_to article_path(@article)
  end
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.haml
= form_with model: article, local: true do |form|
  %div
    = form.label :title
    %br
    = form.text_field :title
    - @article.errors.full_messages_for(:title).each do |message|
      %div= message

  %div
    = form.label :body
    %br
    = form.text_area :body
    - @article.errors.full_messages_for(:body).each do |message|
      %div= message

  %div= form.submit

app/views/articles/edit.html.haml
%h1 Edit article

= render "form", article: @article

- if @article.may_archive?
  %p= link_to 'Archive article', archive_article_path(@article), method: :post

app/views/articles/index.html.haml
%h1 Articles

Our blog has #{Article.public_count} articles and counting!

%ul
  - @articles.each do |article|
    - unless article.archived?
      %li
        = link_to article.title, article

= link_to "New article", new_article_path

app/views/articles/new.html.haml
%h1 New article

= render "form", article: @article

app/views/articles/show.html.haml
%h1= @article.title
%p= @article.body
%ul
  %li= link_to "Edit", edit_article_path(@article)
  %li= link_to "Destroy", article_path(@article),
                          method: :delete,
                          data: { confirm: "Are you sure?" }

%h2 Comments:
= render @article.comments

%h2 Add a comment:
= render 'comments/form'

app/views/comments/_comment.html.haml
%p
  %strong Commenter:
  = comment.commenter
%p
  %strong Comment:
  = comment.body

%p= link_to "Destroy", [comment.article, comment],
      method: :delete,
      data: { confirm: "Are you sure?" }

app/views/comments/_form.html.haml
= form_with model: [ @article, @article.comments.build ], local: true do |form|
  %p
    = form.label :commenter
    %br
    = form.text_field :commenter
  %p
    = form.label :body
    %br
    = form.text_area :body
  %p= form.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Blog
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield